brokers:
    - host: m21.cloudmqtt.com
      port: 18663
      clientId: testclient1
      username: fzofpyze
      password: K3pBZXtF3nM0
      topics: 
        - test1 # topic to subscribe
        - test2
      # last will and testament specified in mqtt
      # will:
      #    topic: <topic> # topic to publish disconnect msg
      #    payload: <disconnect message> # payload disconnect msg
      #    qos: <qos> # qos required from broker
      #    retain: <retain flag> # should the state of the topic be stored

    - host: test.mosquitto.org
      port: 1883
      clientId: testclient2
      topics: 
        - test3 # topic to subscribe
        - test4
      # last will and testament specified in mqtt
      # will:
      #    topic: <topic> # topic to publish disconnect msg
      #    payload: <disconnect message> # payload disconnect msg
      #    qos: <qos> # qos required from broker
      #    retain: <retain flag> # should the state of the topic be stored
