alarmBroker:
  host: localhost
  port: 1883
  topics:
    - alarmtest1
    - alarmtest2

#vesselBroker:
#  host: localhost
#  port: 1883
#  topics:
#    - vessel1
#    - vessel2

pcs: http://localhost:9999
