broker:
  host: 35.202.162.166
  port: 1883
  topics:
    - topic1
    - topic2

vessel:
  boat: MAERSK ADRIATIC
  status: Expected
  arrival: 6/5/2018
  departure: 6/6/2018
  destination: VLC
  terminal: TCV STEVEDORING COMPANY S.A.
